// src/app/layout.tsx
import 'antd/dist/reset.css';
import './globals.css';
import React from "react";
import {ReduxProvider} from "../providers/reduxProvider";

// import type { Metadata } from 'next';
//
// export const metadata: Metadata = {
//     title: 'Task Dashboard',
//     description: 'Generated by create next app',
// };

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body cz-shortcut-listen="true">
        <ReduxProvider>
        {children}
        </ReduxProvider>
        </body>
        </html>
    );
}